### ISSUE TITLE
could you change your file structure?

### ISSUE THREAD

**Issue by bubifengyun** [mbbill/echofunc#6]
i see many vim plugin's structure like this
-<root folder>
--plugin
---****
--README.md
so i can change the folder to ~/.vim/bundle, then
```bash
 git clone https://github.com/mbbill/echofunc.git
```
I don't know very much. Maybe my suggestion is wrong. 
Thank you.

**Comment by mbbill** [comment]
For some reason, it's better to put this plugin into 'after' rather than 'plugin',  you may follow the instructions in README to make it work with pathogen ( other plugin managers should also work I suppose, if not please send me a bug :) )

**Comment by bubifengyun** [comment]
i have installed  successfully. :+1:
